### PR TITLE
Improve performance by using pValue passed in from ssb-db2 3.4

### PR DESCRIPTION
**Pull request by arj03**
Similar to https://github.com/ssbc/ssb-threads/pull/16

### CODE REVIEW

**Comment by staltz** [comment]
My CI tests are embarrassing, :sweat_smile: , give me a minute.

**Comment by arj03** [comment]
Hopefully with these merged performance should improve a bit in manyverse :)

**Comment by staltz** [comment]
The CI can't handle creating the ssb-fixtures, I'll just merge. :upside_down_face:

**Comment by staltz** [comment]
Oh I know what's changed. The new ssb-db2 uses `sbot.db2migrate.progress()` instead of events emitted on the EventEmitter `ssb:db2:migrate:progress`. I changed that and now the tests pass.

Anyway, thanks a lot for updating this!

(Perhaps we also have ssb-friends to update?)

**Comment by arj03** [comment]
Right, I'll fix that one as well :)

**Pull request merged**
