### PR TITLE
Get to run on node 18

### PR DESCRIPTION
**Pull request by Powersource**
Or idk if it's node 18 specifically that broke it, but when i pulled the repo 1. it didn't manage to `pnpm i` because of rsjs and 2. tests didn't pass because of a few small issues.

Needed as part of https://gitlab.com/ahau/ahau/-/issues/34 where one of the tasks is listed as "ssb-profile, optimize the Find by using ssb-search2 (need to modify ssb-search2 for that)". I'll make another PR for that change.

### CODE REVIEW

**Comment by Powersource** [comment]
damn how is rsjs managing to sneak into ci

**Comment by Powersource** [comment]
passing locally and installing in ci now, but getting this in ci

```
✖ four posts
    -------------
      operator: equal
      expected: 4
      actual:   2
      at: <anonymous> (/home/runner/work/ssb-search2/ssb-search2/test/index.js:72:9)
      stack: |-
  Error: four posts
  at Test.assert [as _assert] (/home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/tape@5.7.3/node_modules/tape/lib/test.js:479:48)
  at Test.strictEqual (/home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/tape@5.7.3/node_modules/tape/lib/test.js:661:7)
  at /home/runner/work/ssb-search2/ssb-search2/test/index.js:72:9
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/reduce.js:10:5
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/drain.js:26:24
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/filter.js:17:11
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/flatten.js:35:20
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/map.js:19:9
  at readable (/home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/jitdb@7.0.7_async-append-only-log@4.3.10/node_modules/jitdb/operators.js:444:7)
  at /home/runner/work/ssb-search2/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/map.js:11:7
```

**Comment by Powersource** [comment]
hmm can't actually find evidence this module ever passed in ci, so gonna call in the reviewers anyway :shrug:

**Review by staltz — APPROVED** [review]
Yeah, pretty innocent PR to merge. Thanks.

**Comment by staltz** [comment]
I merged it myself because I have the npm access, and want to publish this now. As a major, I guess, because of breaking changes in ssb-db2 going downstream.

**Comment by staltz** [comment]
Also invited you to npm owner this.

**Pull request merged**
